all:
  cafea:
    # Group for Cafe A (10.0.1.15)
    datacentre_a:
      hosts:
        cafewin1:
          ansible_host: 10.0.1.15
          ansible_user: ansible # Example: Different user for this DC
    
    # Group for Cafe B B (10.1.2.52)
    cafeb:
      hosts:
        cafewin1:
          ansible_host: 10.1.2.52
          ansible_user: ansible # Example: Different user for this DC
