all:
  children:
    # Group for Datacenter A (10.0.1.15)
    datacentre_a:
      hosts:
        cafewin1:
          ansible_host: 10.0.1.15
          ansible_user: user_a # Example: Different user for this DC
    
    # Group for Datacenter B (10.1.2.52)
    datacentre_b:
      hosts:
        cafewin1:
          ansible_host: 10.1.2.52
          ansible_user: user_b # Example: Different user for this DC
